vim9script

set nocompatible
g:coc_global_extensions = ['coc-docker', 'coc-json', 'coc-pyright', 'coc-sh', 'coc-lists', 'coc-pairs', 'coc-marketplace', 'coc-prettier', 'coc-explorer']

source ~/.vim/config/basic.vim
source ~/.vim/config/plugins.vim
source ~/.vim/config/keymaps.vim
source ~/.vim/config/ui.vim
source ~/.vim/config/coc.vim
